### ISSUE TITLE
Consider running through a web server

### ISSUE THREAD

**Issue by elifoster** [retep998/ircbutt-rs#7]
So that you never need to remember to start BunnyButt, or shut it down while your computer is not able to run it, you could consider running it as a web application like I do with LittleHelper. 

[Here's a good example of a web application written in Rust fully compatible with Heroku](https://github.com/emk/heroku-rust-cargo-hello). The only change you'd need to make from that example repo is a Procfile similar to the one in the SatanicBot repo, rather than actually running a web server:

```
web: echo "foobar" > /dev/null
bot: cargo run
```

**Comment by retep998** [comment]
Why would I run it as a web application? There's no web interface to the bot, how would that even work? All I'd need is some sort of server to run the bot on, that's it.

**Comment by elifoster** [comment]
That's what I meant.

**Comment by retep998** [comment]
Not web server. Just any server. A random VPS. Anything that gives me at least SSH access with a shell so I can run arbitrary code. The web has absolutely nothing to do with it.

**Comment by elifoster** [comment]
Right, but my suggestion was specifically heroku, which hosts web servers. It's incredibly easy to set up and use Heroku for this sort of thing, which is why I suggested it specifically.

**Comment by elifoster** [comment]
@retep998 for the record, I'm like 95% sure that sleep time only effects the web dynos.
